import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { ThemeProvider } from "@/components/MaterialUI/MaterialUI";
import MegaMenuDefault from "@/components/Nav/Nav";
import NavServer from "@/components/Nav/NavServer";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = useLocale();
  return (
    <NextIntlClientProvider>
      <ThemeProvider>
        <html lang={locale}>
          <body className={inter.className}>
            <NavServer />

            {children}
          </body>
        </html>
      </ThemeProvider>
    </NextIntlClientProvider>
  );
}
