const LOCAL_STORAGE_KEYS = {
  SELECTED_INDUSTRY: "selectedIndustry",
};

const SVG_IMAGES = {
  FINANCIAL: "FINANCIAL",
  PHARMACEUTICAL: "PHARMACEUTICAL",
  RETAIL: "RETAIL",
  TECHNOLOGY: "TECHNOLOGY",
  CONSTRUCTION: "CONSTRUCTION",
  PRODUCTION: "PRODUCTION",
  ENERGY: "ENERGY",
};

const CONTENT_ITEM_TYPE = {
  PARAGRAPH: "PARAGRAPH",
  LIST: "LIST",
  IMAGE: "IMAGE",
};

export { LOCAL_STORAGE_KEYS, SVG_IMAGES, CONTENT_ITEM_TYPE };
