const LOCAL_STORAGE_KEYS = {
  SELECTED_INDUSTRY: "selectedIndustry",
};

const SVG_IMAGES = {
  FINANCIAL: "FINANCIAL",
  PHARMACEUTICAL: "PHARMACEUTICAL",
  RETAIL: "RETAIL",
  TECHNOLOGY: "TECHNOLOGY",
  CONSTRUCTION: "CONSTRUCTION",
  PRODUCTION: "PRODUCTION",
  ENERGY: "ENERGY",
};

export { LOCAL_STORAGE_KEYS, SVG_IMAGES };
